services:
  - type: web
    name: ignition-portal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -b 0.0.0.0:5000 app:app"
    plan: free
    envVars:
      - key: GITHUB_TOKEN_ENV
        sync: false
      - key: GITHUB_REPO
        value: Team-Vegavath/Ignition1.0
      - key: FLASK_SECRET_KEY
        sync: false
